### ISSUE TITLE
Wrong hints

### ISSUE THREAD

**Issue by utking** [jtsunne/golastic#17]
When you open the index tab, it says at the bottom that Ctrl+O and Ctrl+I can be used to sort the indices. But in reality, Shift+O and Shift+I are used.
Same seems to be the case for a bunch of other actions

**Comment by jtsunne** [comment]
Yes, it happened coz I switched from Global hotkeys to Hotkey per Page. It will be fixed soon

**Comment by jtsunne** [comment]
And not only Shift-I/O is working 'I/o' (without SHIFT) is working too :)

**Comment by jtsunne** [comment]
Fixed in Master branch
