### ISSUE TITLE
Allow "opening" the currently selected index

### ISSUE THREAD

**Issue by utking** [jtsunne/golastic#4]
I think it can be useful to have some more information about indices. If we select one index in the list and press Enter (or something another key), the application can show details about the index (for example, where its shards are located) and maybe allow some index actions for this particular index.

**Comment by jtsunne** [comment]
Probably "opening" means - Show Index Statistics. Is it OK?

**Comment by utking** [comment]
> Probably "opening" means - Show Index Statistics. Is it OK?

Yes, the index statistics that includes where (on what nodes) the index's shards are located. Perhaps there is something else you see will be useful.

**Comment by utking** [comment]
It still does not show where the index's shards are located.

**Comment by jtsunne** [comment]
For Shards plans independent Page
